//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanezPower
{


    public partial class STOCKOUT
    {

        protected global::System.Web.UI.WebControls.DropDownList DROPPART;
        protected global::System.Web.UI.WebControls.DropDownList DROPSITE;
        protected global::System.Web.UI.WebControls.DropDownList DROPTEAM;
        protected global::System.Web.UI.WebControls.DropDownList DROPGENSET;
        protected global::System.Web.UI.WebControls.DropDownList DROPCAMPO;
       
        protected global::System.Web.UI.WebControls.Label LBLESTADO;
        protected global::System.Web.UI.WebControls.Label LBLESTADO0;
        protected global::System.Web.UI.WebControls.Label LBLESTADO1;
        protected global::System.Web.UI.WebControls.TextBox TXTSERIAL;
        protected global::System.Web.UI.WebControls.TextBox TXTDATE;
        protected global::System.Web.UI.WebControls.TextBox TXTQTY;
        protected global::System.Web.UI.WebControls.TextBox TXTCANTI;
        protected global::System.Web.UI.WebControls.TextBox TXTDESCRIPTION;
        protected global::System.Web.UI.WebControls.TextBox TXTDESCRIPTION0;

        protected global::System.Web.UI.WebControls.TextBox TextBox1;

        protected global::System.Web.UI.WebControls.GridView GridView1;
        protected global::System.Web.UI.WebControls.TextBox TXTACCPAC;
        protected global::System.Web.UI.WebControls.TextBox TXTDESDE;
        protected global::System.Web.UI.WebControls.TextBox TXTHASTA;


        protected global::System.Web.UI.WebControls.Button Button1;

        protected global::System.Web.UI.WebControls.Panel Panel1;




    }
}
