//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanezPower.USUARIO2
{


    public partial class PANEL_CODES
    {
        protected global::System.Web.UI.WebControls.Button BTNGUARDAR;
        protected global::System.Web.UI.WebControls.Button BTNEDIT;
        protected global::System.Web.UI.WebControls.Button BTNDELETE;
        protected global::System.Web.UI.WebControls.TextBox TXTCODE;
        protected global::System.Web.UI.WebControls.TextBox TXTFMI;
        protected global::System.Web.UI.WebControls.TextBox TXTDESCRIPTION;
        protected global::System.Web.UI.WebControls.TextBox TXTUSUARIO;
        protected global::System.Web.UI.WebControls.Button BTNBUSCAR;
        protected global::System.Web.UI.WebControls.DropDownList DROPENGINE;
        protected global::System.Web.UI.WebControls.GridView GridView1;
        protected global::System.Web.UI.WebControls.Label LBLESTADO;
        protected global::System.Web.UI.WebControls.Panel Panel1;

    }
}
