//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanezPower.USUARIO2
{


    public partial class READINGSUMMARY
    {
        protected global::System.Web.UI.WebControls.GridView GridView3;
        protected global::System.Web.UI.WebControls.DropDownList CBSITE;
        protected global::System.Web.UI.WebControls.TextBox txtmesreading;

    }
}
