//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanezPower.USUARIO2
{


    public partial class WAMDY
    {

        protected global::System.Web.UI.WebControls.DropDownList DROPPART;
        protected global::System.Web.UI.WebControls.DropDownList DROPSITE;
        protected global::System.Web.UI.WebControls.DropDownList DROPTEAM;
        protected global::System.Web.UI.WebControls.DropDownList DROPGENSET;
        protected global::System.Web.UI.WebControls.DropDownList DROPCAMPO;

        protected global::System.Web.UI.WebControls.Label LBLESTADO;
        protected global::System.Web.UI.WebControls.Label LBLESTADO0;
        protected global::System.Web.UI.WebControls.TextBox TXTSERIAL;
        protected global::System.Web.UI.WebControls.TextBox TXTDATE;
        protected global::System.Web.UI.WebControls.TextBox TXTQTY;
        protected global::System.Web.UI.WebControls.TextBox TXTCANTI;
        protected global::System.Web.UI.WebControls.TextBox TXTDESCRIPTION;
        protected global::System.Web.UI.WebControls.TextBox TXTDESCRIPTION0;

        protected global::System.Web.UI.WebControls.TextBox TextBox1;

        protected global::System.Web.UI.WebControls.GridView GridView1;
        protected global::System.Web.UI.WebControls.TextBox TXTACCPAC;
        protected global::System.Web.UI.WebControls.TextBox TXTDESDE;
        protected global::System.Web.UI.WebControls.TextBox TXTHASTA;
        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;
        protected global::System.Web.UI.WebControls.TextBox TXTUSUARIO;

        protected global::System.Web.UI.WebControls.TextBox txtcliente;
        protected global::System.Web.UI.WebControls.TextBox txtsite;
        protected global::System.Web.UI.WebControls.TextBox txtmotorreff;
        protected global::System.Web.UI.WebControls.TextBox txtcapacity;

        protected global::System.Web.UI.WebControls.TextBox txtmotorserial;
        protected global::System.Web.UI.WebControls.TextBox txtdescripcion;
        protected global::System.Web.UI.WebControls.TextBox txtdateout;
        protected global::System.Web.UI.WebControls.TextBox txtinvoice;
        protected global::System.Web.UI.WebControls.TextBox txttotal;
        protected global::System.Web.UI.WebControls.TextBox txtestatus;
        protected global::System.Web.UI.WebControls.TextBox txtmarray;
        protected global::System.Web.UI.WebControls.TextBox txtcpdinv;
        protected global::System.Web.UI.WebControls.TextBox txtcpdtotal;
        protected global::System.Web.UI.WebControls.TextBox txtcpdinvstatus;
        protected global::System.Web.UI.WebControls.TextBox TXTNOTAS;



        protected global::System.Web.UI.WebControls.Button BTNBUSCAR, BTNSAVE, BTNEDIT, BTNDELETE;




        protected global::System.Web.UI.WebControls.Panel Panel1;

        protected global::System.Web.UI.WebControls.FileUpload FileUpload1;








    }
}
