//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanezPower.USUARIO1
{


    public partial class FUELUSE
    {
        protected global::System.Web.UI.WebControls.DropDownList DROPTEAM;
        protected global::System.Web.UI.WebControls.DropDownList DROPVEHICLE;
        protected global::System.Web.UI.WebControls.DropDownList DROPFUELTYPE;
        protected global::System.Web.UI.WebControls.DropDownList DROPFROM;
        protected global::System.Web.UI.WebControls.DropDownList DROPCAMPO;
        protected global::System.Web.UI.WebControls.TextBox TXTDATE;
        protected global::System.Web.UI.WebControls.TextBox TXTNOTE;
        protected global::System.Web.UI.WebControls.TextBox TXTQTY;
        protected global::System.Web.UI.WebControls.TextBox TXTBUSCAR;
        protected global::System.Web.UI.WebControls.TextBox TXTDESDE;
        protected global::System.Web.UI.WebControls.TextBox TXTHASTA1;
        protected global::System.Web.UI.WebControls.GridView GridView1;
        protected global::System.Web.UI.WebControls.Button BTNDELETE;
        protected global::System.Web.UI.WebControls.Button BTNEDIT;
        protected global::System.Web.UI.WebControls.Button BTNSAVE;
        protected global::System.Web.UI.WebControls.Button Button6;
        protected global::System.Web.UI.WebControls.Panel Panel1;
        protected global::System.Web.UI.WebControls.Label LBLESTADO0, LBLESTADO1;

    }
}
