//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanezPower.USUARIO1
{


    public partial class Reading
    {

        protected global::System.Web.UI.WebControls.DropDownList CBSITE;
        protected global::System.Web.UI.WebControls.GridView GridView1;
        protected global::System.Web.UI.WebControls.GridView GridView2;
        protected global::System.Web.UI.WebControls.GridView GridView3;
        protected global::System.Web.UI.WebControls.GridView GridView4;


        protected global::System.Web.UI.WebControls.GridView GridView5;
        protected global::System.Web.UI.WebControls.GridView GridView6;
        protected global::System.Web.UI.WebControls.DropDownList DROPCLIEN;
        protected global::System.Web.UI.WebControls.Label LBLESTADO;
        protected global::System.Web.UI.WebControls.Label LBLESTADO0;
        protected global::System.Web.UI.WebControls.Label Label1;



        protected global::System.Web.UI.WebControls.TextBox txthoras;
        protected global::System.Web.UI.WebControls.TextBox txtenergy;
        protected global::System.Web.UI.WebControls.TextBox txtrate;
        protected global::System.Web.UI.WebControls.TextBox txthoras0;
        protected global::System.Web.UI.WebControls.TextBox txtenergy0;
        protected global::System.Web.UI.WebControls.TextBox txtrate0;


        protected global::System.Web.UI.WebControls.TextBox txtmesreading;
        protected global::System.Web.UI.WebControls.TextBox txtmeslasreading;
        protected global::System.Web.UI.WebControls.TextBox txtnotas;

        protected global::System.Web.UI.WebControls.Button BTNSAVE;


    }
}
